version: '3.8'

services:
  sync_simak:
    build: Sync/.
    image: adamilkom00/sync:1.0.1
    container_name: sync_simak
    depends_on:
      db_simak:
        #condition: service_healthy  # Tunggu sampai DB siap
    environment:
      ConnectionString__SOURCE: "host2:host22017@tcp(remote-simak:30130)/unpak_simak"
      ConnectionString__TARGET: "root:251423@tcp(db_simak:3306)/sync_simak"  
    ports:
      - "81:8080"
    extra_hosts:
      - "remote-simak:172.16.21.3"

  db_simak:
    image: mariadb:latest
    container_name: db_simak
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 251423
      MYSQL_DATABASE: sync_simak
    command: >
      --log-bin=mysql-bin
      --binlog-format=ROW
      --server-id=10
      --binlog-row-image=FULL
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
