version: '3.8'

services:
  db_target:
    image: mariadb:latest
    container_name: db_target
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 251423
      MYSQL_DATABASE: sync_target
    command: >
      --port=3307
      --log-bin=mysql-bin
      --binlog-format=ROW
      --server-id=10
      --binlog-row-image=FULL
    ports:
      - "3308:3307"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - sample
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  sync_simak:
    # build: Sync/.
    image: adamilkom00/sync:1.0.4
    container_name: sync_simak
    depends_on:
      - db_target
    environment:
      ConnectionString__SOURCE: "host2:host22017@tcp(remote-simak:30130)/unpak_simak?charset=utf8mb4&parseTime=True&loc=Local"
      ConnectionString__TARGET: "root:251423@tcp(db_target:3307)/sync_target?charset=utf8mb4&parseTime=True&loc=Local"
    ports:
      - "81:3000"
    extra_hosts:
      - "remote-simak:172.16.21.3"
    networks:
      - sample

  sync_simpeg:
    # build: Sync/.
    image: adamilkom00/sync:1.0.4
    container_name: sync_simpeg
    depends_on:
      - db_target
    environment:
      ConnectionString__SOURCE: "simpegunpak:simp3gunp4k2017@tcp(remote-simpeg:3306)/unpak_simpeg?charset=utf8mb4&parseTime=True&loc=Local"
      ConnectionString__TARGET: "root:251423@tcp(db_target:3307)/sync_target?charset=utf8mb4&parseTime=True&loc=Local"
    ports:
      - "82:3000"
    extra_hosts:
      - "remote-simpeg:172.16.20.245"
    networks:
      - sample

  # sync_simpeg:
  #   build: Sync/.
  #   image: sync:1.0.4
  #   container_name: sync_simpeg
  #   depends_on:
  #     - db_target
  #       # condition: service_healthy
  #   environment:
  #     ConnectionString__SOURCE: "simpegunpak:simp3gunp4k2017@tcp(remote-simpeg:3306)/unpak_simpeg"
  #     ConnectionString__TARGET: "root:251423@tcp(db_target:3307)/sync_target?charset=utf8mb4&parseTime=True&loc=Local"
  #   ports:
  #     - "82:3000"
  #   extra_hosts:
  #     - "remote-simpeg:172.16.20.245"
  #   networks:
  #     - sample

networks:
  sample:
    driver: bridge
