version: '3.8'

services:
  sync_simak:
    build: Sync/.
    image: adamilkom00/sync:1.0.1
    container_name: sync_simak
    depends_on:
      - db_simak
    environment:
      ConnectionString__SOURCE: "host2:host22017@tcp(remote-simak:30130)/unpak_simak"
      ConnectionString__TARGET: "root:251423@tcp(localhost:3307)/sync_simak"  
    ports:
      - "81:8080"
    extra_hosts:
      - "remote-simak:172.16.21.3"

  sync_simpeg:
    build: Sync/.
    image: adamilkom00/sync:1.0.1
    container_name: sync_simpeg
    depends_on:
      - db_simpeg
    environment:
      ConnectionString__SOURCE: "simpegunpak:simp3gunp4k2017@tcp(remote-simpeg:3306)/unpak_simpeg"
      ConnectionString__TARGET: "root:251423@tcp(localhost:3308)/sync_simpeg"  
    ports:
      - "82:8080"
    extra_hosts:
      - "remote-simpeg:172.16.20.245"

  db_simak:
    image: mariadb:latest
    container_name: db_simak
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 251423
      MYSQL_DATABASE: sync_simak
    command: >
      --log-bin=mysql-bin
      --binlog-format=ROW
      --server-id=10
      --binlog-row-image=FULL
    ports:
      - "3307:3306"

  db_simpeg:
    image: mariadb:latest
    container_name: db_simpeg
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 251423
      MYSQL_DATABASE: sync_simpeg
    command: >
      --log-bin=mysql-bin
      --binlog-format=ROW
      --server-id=20
      --binlog-row-image=FULL
    ports:
      - "3308:3306"
